version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672  # amqp protocol
      - 15672:15672  # rabbitmq management ui
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf  # mount custom configuration file
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=admin
        - MONGO_INITDB_DATABASE=btgPactual
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
        - ME_CONFIG_BASICAUTH_USERNAME=root
        - ME_CONFIG_BASICAUTH_PASSWORD=admin
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    links:
      - mongo
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:

