version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: [3000:3000]
    depends_on: [rabbitmq, mongodb]
    volumes: [.:/usr/src/app]
    environment: [NODE_ENV=development]
    networks: [app-network]
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672  # AMQP protocol
      - 15672:15672  # RabbitMQ management UI
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf  # Mount custom configuration file
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks: [app-network]
  mongodb:
    image: mongo:latest
    ports: [27017:27017]
    volumes: [mongodb_data:/data/db]
    networks: [app-network]
networks:
  app-network:
    driver: bridge
volumes:
  mongodb_data:
